
const colors = {
  normal: '#c6c6a7',
  fire: '#f5ac78',
  water: '#9db7f5',
  electric: '#fae078',
  grass: '#a7db8d',
  ice: '#bce6e6',
  fighting: '#d67873',
  poison: '#c183c1',
  ground: '#ebd69d',
  flying: '#c6b7f5',
  psychic: '#fa92b2',
  bug: '#c6d16e',
  rock: '#d1c17d',
  ghost: '#a292bc',
  dragon: '#a27dfa',
  dark: '#a19288',
  steel: '#d1d1e0',
  fairy: '#f4bdc9',
  unknown: '#9dc1b7',
}

const icons = {
  normal: 'icons/normal.svg',
  fire: 'icons/fire.svg',
  water: 'icons/water.svg',
  electric: 'icons/electric.svg',
  grass: 'icons/grass.svg',
  ice: 'icons/ice.svg',
  fighting: 'icons/fighting.svg',
  poison: 'icons/poison.svg',
  ground: 'icons/ground.svg',
  flying: 'icons/flying.svg',
  psychic: 'icons/psychic.svg',
  bug: 'icons/bug.svg',
  rock: 'icons/rock.svg',
  ghost: 'icons/ghost.svg',
  dragon: 'icons/dragon.svg',
  dark: 'icons/dark.svg',
  steel: 'icons/steel.svg',
  fairy: 'icons/fairy.svg',
  unknown: 'icons/unknown.svg',
}

const classPokemons = {
  normal: 'normal',
  fire: 'fire',
  water: 'water',
  electric: 'electric',
  grass: 'grass',
  ice: 'ice',
  fighting: 'fighting',
  poison: 'poison',
  ground: 'ground',
  flying: 'flying',
  psychic: 'psychic',
  bug: 'bug',
  rock: 'rock',
  ghost: 'ghost',
  dragon: 'dragon',
  dark: 'dark',
  steel: 'steel',
  fairy: 'fairy',
  unknown: 'unknown',
}
